# Generated by Django 3.2.5 on 2021-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('hyperlink', models.URLField(blank=True)),
                ('icon', models.CharField(max_length=50)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
