# Generated by Django 3.2.5 on 2021-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=50)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('info', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='customers')),
            ],
        ),
    ]
