# Generated by Django 3.2.5 on 2021-08-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0002_skill_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=256)),
                ('image', models.ImageField(upload_to='profile')),
                ('image_circle', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
