# Generated by Django 3.2.5 on 2021-08-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0003_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='image_circle',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
