# Generated by Django 3.2.5 on 2021-08-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0004_auto_20210801_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='practice',
            field=models.TextField(blank=True),
        ),
    ]
